name: ZAP Baseline Scan

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: 'Target URL to scan'
        required: true
        default: 'https://example.com'

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set executable permission for script
        run: chmod +x scripts/zap_baseline_scan.sh

      - name: Run ZAP scan script
        run: ./scripts/zap_baseline_scan.sh "${{ github.event.inputs.target_url }}"

      - name: Upload ZAP report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap_report.html
