name: ZAP Scan Workflow

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: 'Target URL to scan'
        required: true
        default: 'https://example.com'

jobs:
  zap-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: ZAP Baseline Scan
        run: |
          docker run --rm -v $(pwd):/zap/wrk/:rw -t ghcr.io/zaproxy/zap-baseline:latest \
          -t "${{ github.event.inputs.target_url }}" \"
          -g gen.conf -r zap_report.html || true

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v3
        with: 
          name: zap_report
          path: zap_report.html

