name: ZAP Baseline Scan Workflow

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: 'Target URL to scan'
        required: true
        default: 'https://example.com'

jobs:
  zap-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make scan script executable
        run: chmod +x zap_baseline_scan.sh

      - name: Run ZAP Baseline Scan
        run: ./zap_baseline_scan.sh "${{ github.event.inputs.target_url }}"

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap_report
          path: zap_report.html
